#!/usr/bin/env bash
set -x
set -e
mkdir -p m4
mkdir -p .build-aux
git log | grep ^Author: | sort -u | cut -f'2-' -d' ' > AUTHORS
git log --date=short --pretty="[%cd | %h | <%aE>]  %s%n" > ChangeLog
autoreconf --install
