/*---- udon parser header/api - automatically generated by genmachine ----*/
#ifndef __UDON_H__
#define __UDON_H__ 1
#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <stddef.h>
#include <setjmp.h>


/* --- Allow setting different malloc/free routines --- */
#ifdef _UDON_NONSTANDARD_MEMORY
void *udon_calloc(size_t count, size_t size);
void *udon_malloc(size_t size);
void  udon_free(void *ptr, size_t size);
#else

#define udon_calloc(count,size) calloc(count,size)
#define udon_malloc(size)       malloc(size)
#define udon_free(ptr,size)     free(ptr)
#endif

/* --- Error values --- */
#include <sysexits.h>
#define UDON_OK             EX_OK
#define UDON_MEMORY_ERR     EX_OSERR
#define UDON_FILE_OPEN_ERR  EX_NOINPUT
#define UDON_FILE_READ_ERR  EX_IOERR
#define UDON_DATA_ERR       EX_DATAERR

/* --- Global parser error state --- */
extern int udon_global_error;
extern char udon_global_error_msg[128];


struct UdonGmString {
    char *                       start;
    uint64_t                     length;
};
typedef struct UdonGmString      UdonGmString;


struct UdonGmList {
    void *                       v;
    struct UdonList *            next;
};
typedef struct UdonGmList        UdonGmList;

/* --- For hash tables --- */

struct UdonGmEntry {
    UdonGmString *key;
    void *value;
    unsigned int _used;
};
typedef struct UdonGmEntry UdonGmEntry;

struct UdonGmDict {
    UdonGmEntry *table;
    uint64_t size;
    unsigned int filled;
};
typedef struct UdonGmDict UdonGmDict;


/* TODO:
 *  - Linked Lists if needed
 *  - Hash tables if needed
 *  - Strings if needed (can't imagine them not being needed)
 *  - Types / enums as per the source
 *  - Public prototypes
 *
 */

/*
struct UdonGmDict {
    UdonGmList                   keys;
    UdonGmList                   _keys__tail;
    struct hsearch_data *        table;
    uint64_t                     size;
    uint64_t                     allocated;
};
typedef struct UdonGmDict        UdonGmDict;
*/


enum UdonNodeType {
    UDON_ROOT,
    UDON_BLANK,
    UDON_VALUE,
    UDON_FULL
};
typedef enum UdonNodeType        UdonNodeType;



struct UdonNode {
    UdonGmList                   _base;

    UdonNodeType                 node_type;
    uint64_t                     source_line;
    uint64_t                     source_column;
};
typedef struct UdonNode          UdonNode;



struct UdonFullNode {
    UdonNode                     _base;

    UdonNode *                   children;
    UdonNode *                   _children__tail;
    UdonGmString *               name;
    UdonGmString *               id;
    UdonGmList *                 classes;
    UdonGmList *                 _classes__tail;
    UdonGmDict *                 attributes;
};
typedef struct UdonFullNode      UdonFullNode;




/* TODO: move opaque parts into their own struct in the c file with this as a
 *       member
 */
struct UdonParseState {
    // --- Set these ---
    char             *buffer;
    size_t           size;
    char             *filename;  // optional, of course
    jmp_buf          err_jmpbuf; // Use setjmp(...)

    // --- Result State ---
    void             *result;
    unsigned int     error_code;
    char             error_message[256];
    UdonGmList         warnings;

    // --- Current State ---
    unsigned int     state;
    uint64_t         line;
    uint64_t         column;

    // --- Generally Opaque ---
    char             *curr;
    uint64_t         *qcurr;
    char             *end;
    uint64_t         *qend;
    size_t           qsize;  // Automatically calculated, for quickscans.
    char             *alpha; // Used for accumulating
};
typedef struct UdonParseState UdonParseState;


int udon_parse(UdonParseState *p);
static inline UdonFullNode * _udon_node(UdonParseState *p);
static inline UdonGmString * _udon_label(UdonParseState *p);
static inline UdonFullNode * _udon_node__s_child_shortcut(UdonParseState *p);
static inline UdonGmString * _udon_label__s_delim(UdonParseState *p);
static inline void * _udon_id(UdonParseState *p);
static inline void * _udon_comment(UdonParseState *p);
static inline UdonFullNode * _new_udon_full_node(UdonParseState *p);
static inline UdonGmString * _new_udon_gm_string(UdonParseState *p);

#ifdef __cplusplus
}
#endif
#endif
