#!/bin/bash
SCRIPT_PATH="${BASH_SOURCE[0]}";
if [ -h "${SCRIPT_PATH}" ]; then
  while([ -h "${SCRIPT_PATH}" ]) do
    if [[ `uname -s` == 'Darwin' ]]; then
      SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`
    else
      SCRIPT_PATH=`readlink -f "${SCRIPT_PATH}"`
    fi
  done
fi
pushd . > /dev/null
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;

set -e
./genmachine ./udon.machine
mv ./udon.c ../
mv ./udon.h ../

popd  > /dev/null
